# Generated by Django 4.2.6 on 2023-11-26 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitConnect', '0002_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieLog',
            fields=[
                ('calorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('recorded_date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'calorie_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentBank',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'equipment_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseBank',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'exercise_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoalBank',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'goal_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'message_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MuscleGroupBank',
            fields=[
                ('muscle_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'muscle_group_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('water_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('recorded_date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'water_log',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CoachCategory',
        ),
        migrations.DeleteModel(
            name='CoachReview',
        ),
        migrations.DeleteModel(
            name='EquipmentForExercise',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseCategory',
        ),
        migrations.DeleteModel(
            name='ExerciseEquipment',
        ),
        migrations.DeleteModel(
            name='ExerciseMedia',
        ),
        migrations.DeleteModel(
            name='ExerciseMuscleCategory',
        ),
        migrations.DeleteModel(
            name='FitnessGoal',
        ),
        migrations.DeleteModel(
            name='IntakeLog',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ProgressPhoto',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='WeightGoal',
        ),
    ]
