# Generated by Django 4.2.6 on 2023-11-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FitConnect', '0003_calorielog_equipmentbank_exercisebank_goalbank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BecomeCoachRequest',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='FitConnect.user')),
                ('experience', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'become_coach_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminCredentials',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='FitConnect.admin')),
                ('hashed_password', models.CharField(max_length=120)),
                ('created', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_credentials',
                'managed': False,
            },
        ),
    ]
